# id: 1
server:
  address: "server:12345"
loop:
  amount: 8
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 10
client:
  NOMBRE: "Camila Rocio"
  APELLIDO: "Varela"
  DOCUMENTO: "37130775"
  NACIMIENTO: "1995-05-09"
  NUMERO: "4179"